/* eslint-disable @next/next/no-img-element */
import { SiteNav } from "@/components/SiteNav";
import { SiteFooter } from "@/components/SiteFooter";
import { FaqSection } from "@/components/FaqSection";
import { Hero } from "@/components/sections/Hero";
import { Products } from "@/components/sections/Products";
import { Stats } from "@/components/sections/Stats";
import { Features } from "@/components/sections/Features";
import { Templates } from "@/components/sections/Templates";
import { Testimonials } from "@/components/sections/Testimonials";
import { ButtonLink } from "@/components/Button";
import { Reveal } from "@/components/primitives/Reveal";
import { StarsBackground } from "@/components/ui/stars";

function CtaBand() {
  return (
    <section
      id="install"
      className="relative overflow-hidden pt-20 md:pt-24 pb-12 md:pb-16 text-center"
      style={{
        background:
          "radial-gradient(ellipse 90% 85% at 50% 118%, #16397a 0%, #08163a 52%, #030a1e 100%)",
      }}
    >
      {/* subtle dotted pattern */}
      <div
        aria-hidden="true"
        className="absolute inset-0 z-0 pointer-events-none"
        style={{
          backgroundImage: "radial-gradient(rgba(255,255,255,0.09) 1px, transparent 1px)",
          backgroundSize: "24px 24px",
          maskImage: "radial-gradient(ellipse 80% 70% at 50% 40%, #000 30%, transparent 78%)",
          WebkitMaskImage: "radial-gradient(ellipse 80% 70% at 50% 40%, #000 30%, transparent 78%)",
        }}
      />
      <StarsBackground
        aria-hidden="true"
        className="absolute inset-0 z-0"
        style={{ background: "transparent", pointerEvents: "none" }}
        starColor="#ffffff"
        speed={70}
      />
      <div className="container-page relative z-10">
        <Reveal>
          <span id="pricing" className="sr-only">Get Started</span>
          <h2 className="font-display font-medium capitalize text-white tracking-[-0.5px] leading-[1.05] text-[clamp(28px,4.4vw,56px)] max-w-[18ch] mx-auto">
            Your Next Presentation Is One Prompt Away
          </h2>
          <p className="font-sans text-white/70 text-[17px] leading-[1.6] mt-5 max-w-[42ch] mx-auto">
            Skip the blank slide. Describe the deck and start presenting.
          </p>
          <div className="flex flex-wrap items-center justify-center gap-3 mt-8">
            <ButtonLink href="https://www.imagine.art/computer/agent/slides" variant="white" size="lg">
              Generate your deck
            </ButtonLink>
          </div>
        </Reveal>

        {/* fanned showcase of generated decks */}
        <Reveal delay={140}>
          <div className="relative mx-auto mt-10 md:mt-14 w-full max-w-[820px] h-[180px] sm:h-[260px] md:h-[320px]">
            <img
              src="/assets/deck-proposal.png"
              alt=""
              aria-hidden="true"
              className="absolute left-1/2 bottom-6 w-[48%] -translate-x-[104%] rotate-[-8deg] z-10 drop-shadow-[0_28px_60px_rgba(0,0,0,0.55)]"
            />
            <img
              src="/assets/deck-platform.png"
              alt=""
              aria-hidden="true"
              className="absolute left-1/2 bottom-6 w-[48%] translate-x-[4%] rotate-[8deg] z-10 drop-shadow-[0_28px_60px_rgba(0,0,0,0.55)]"
            />
            <img
              src="/assets/deck-botanical.png"
              alt="A presentation deck generated by AI Slides"
              className="absolute left-1/2 bottom-0 w-[54%] -translate-x-1/2 z-20 drop-shadow-[0_36px_70px_rgba(0,0,0,0.6)]"
            />
          </div>
        </Reveal>
      </div>
    </section>
  );
}

export default function Home() {
  return (
    <>
      <SiteNav />
      <main>
        <Hero />
        <div
          className="relative"
          style={{
            background:
              "linear-gradient(180deg, #ffffff 0%, #DCEEFF 14%, #BFE4FF 30%, #CFF0FF 54%, #EAF5FF 82%, #ffffff 100%)",
          }}
        >
          {/* artistic film-grain over the sky gradient */}
          <div
            aria-hidden="true"
            className="pointer-events-none absolute inset-0 z-0 mix-blend-soft-light opacity-[0.5]"
            style={{
              backgroundImage:
                "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E\")",
              backgroundSize: "140px 140px",
            }}
          />
          <div className="relative z-10">
            <Products />
            <Stats />
          </div>
        </div>
        <Features />
        <Templates />
        <Testimonials />
        <FaqSection />
        <CtaBand />
      </main>
      <SiteFooter />
    </>
  );
}
